name: DevSkim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: DevSkim
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
     - uses: actions/checkout@v2
     - uses: microsoft/DevSkim-Action@v1
     - uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: devskim-results.sarif

     - name: Run DevSkim scanner
       uses: microsoft/DevSkim-Action@v1
        
     - name: Upload DevSkim scan results to GitHub Security tab
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: devskim-results.sarif
